export interface IndustryTemplate {
  id: string;
  name: string;
  icon: string;
  description: string;
  extractPromptAddition: string;
  buildPromptAddition: string;
  defaultDeliverables: string[];
  commonRisks: string[];
  defaultClauses: string[];
  clarifyingQuestions: string[];
}

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: "brand-design",
    name: "Brand Design",
    icon: "🎨",
    description: "Logo, identity, brand guidelines",
    extractPromptAddition: `This is a brand design project. Pay special attention to: number of logo concepts to present, brand guideline requirements, file format deliverables (AI, EPS, PNG, PDF), color palette and typography needs, primary vs secondary logo variations, icon or favicon requirements, brand application examples needed (mockups, stationery etc). Flag risks around: vague aesthetic direction, no reference brands provided, unclear usage rights (print vs digital vs merchandise).`,
    buildPromptAddition: `Generate scope for a brand design project. Standard industry inclusions: primary logo, color palette, typography selection, brand usage guidelines. Standard exclusions: print production, website design, social media content unless specified. Include clauses about: number of initial concepts presented (typically 2-3), revision rounds per concept, file ownership transfer on final payment, usage rights (digital/print/merchandise), kill fee if project cancelled after concepts presented.`,
    defaultDeliverables: [
      "Primary logo in full color, reversed, and monochrome",
      "Brand color palette with hex, RGB, and CMYK values",
      "Typography selection with primary and secondary typefaces",
      "Logo usage guidelines document (PDF)",
      "Final files in AI, EPS, PNG, PDF, and SVG formats",
      "Brand style guide (up to 10 pages)",
    ],
    commonRisks: [
      "Client has no reference brands or visual direction",
      "Scope of brand applications unclear (print, digital, merchandise)",
      "Number of logo concepts not defined",
      "File ownership and usage rights not discussed",
      "Revision rounds not capped",
    ],
    defaultClauses: [
      "1. Concepts: This project includes presentation of 2 initial logo concepts. The client will select one direction for refinement.",
      "2. Revisions: Each phase includes 2 rounds of revisions. Additional revisions are billed at the agreed hourly rate.",
      "3. Ownership: All intellectual property rights transfer to the client upon receipt of final payment in full.",
      "4. Usage: Files are provided for digital and print use. Merchandise and resale usage requires a separate licensing agreement.",
      "5. Kill Fee: If the project is cancelled after initial concepts are presented, 50% of the remaining project fee is due.",
      "6. Credit: The contractor reserves the right to display completed work in their portfolio unless otherwise agreed in writing.",
    ],
    clarifyingQuestions: [
      "Do you have any existing brand elements (colors, fonts, style) that must be incorporated or avoided?",
      "Can you share 3-5 brands whose visual style you admire as reference?",
      "What formats do you need the final files in? (print, digital, merchandise)",
      "How many initial logo concepts would you like to see?",
      "Do you need a full brand guidelines document or just logo files?",
      "Will this brand appear on any physical products or merchandise?",
    ],
  },
  {
    id: "web-design",
    name: "Web Design",
    icon: "🖥️",
    description: "Website design and development",
    extractPromptAddition: `This is a web design or development project. Pay special attention to: exact number of pages, CMS requirements (WordPress, Webflow, Shopify etc), mobile responsiveness, browser compatibility requirements, hosting and domain situation, contact forms or other interactive elements, SEO requirements, content provision responsibility, go-live support needed. Flag risks around: vague page count, no content ready, unclear CMS preference, hosting not discussed.`,
    buildPromptAddition: `Generate scope for a web design/development project. Standard inclusions: agreed pages list, mobile responsive design, one contact form, basic on-page SEO setup, browser testing (Chrome, Safari, Firefox), 1 hour training on CMS if applicable. Standard exclusions: ongoing maintenance, hosting costs, domain registration, copywriting, photography, e-commerce unless specified. Include clauses about: content must be provided by client by specific date, timeline dependent on client feedback within 3 business days, hosting and ongoing maintenance quoted separately.`,
    defaultDeliverables: [
      "Fully designed and developed website with agreed pages",
      "Mobile responsive design tested on iOS and Android",
      "Contact form with email notification",
      "Basic on-page SEO (meta titles, descriptions, alt tags)",
      "Cross-browser testing (Chrome, Safari, Firefox, Edge)",
      "CMS training session (1 hour) if applicable",
      "Go-live support and launch checklist",
    ],
    commonRisks: [
      "Exact page count not defined",
      "Client has no content ready — will delay project significantly",
      "CMS preference not confirmed",
      "Hosting and domain situation unclear",
      "E-commerce functionality scope unclear",
    ],
    defaultClauses: [
      "1. Content: Client is responsible for providing all written content, images, and assets by the agreed content deadline. Delays caused by late content may affect the project timeline.",
      "2. Revisions: This project includes 2 rounds of design revisions per page template. Additional revisions are billed at the agreed hourly rate.",
      "3. Hosting: Website hosting, domain registration, and ongoing maintenance are not included and will be quoted separately.",
      "4. Browser Support: The website will be tested on the latest versions of Chrome, Safari, Firefox, and Edge. Legacy browser support is not included.",
      "5. Feedback: Client agrees to provide feedback within 3 business days of each deliverable. Delays beyond this may affect the project timeline.",
      "6. Launch: A staging environment will be provided for review before go-live. Client sign-off is required before the site goes live.",
    ],
    clarifyingQuestions: [
      "How many pages does the website need? Please list them.",
      "Do you need a CMS so you can edit content yourself? If so, do you have a preference (WordPress, Webflow, Squarespace)?",
      "Do you have content (text and images) ready, or does this need to be sourced?",
      "What is your current hosting situation — do you have a host and domain already?",
      "Do you need any e-commerce, booking, or membership functionality?",
      "Are there any existing brand guidelines or design styles to follow?",
    ],
  },
  {
    id: "copywriting",
    name: "Copywriting",
    icon: "✍️",
    description: "Website copy, content, and writing",
    extractPromptAddition: `This is a copywriting or content project. Pay special attention to: word count or page count, tone of voice requirements, target audience definition, SEO keyword requirements, number of revision rounds, content format (website, blog, ads, email), brand voice guidelines existence. Flag risks around: no word count defined, no audience brief, unclear approval process, SEO requirements undefined.`,
    buildPromptAddition: `Generate scope for a copywriting project. Standard inclusions: agreed page or word count, one round of structural revisions, one round of copy revisions, final proofread, delivery in Google Doc or Word format. Standard exclusions: SEO keyword research unless specified, translation, design layout, image sourcing. Include clauses about: client to provide brand voice guidelines and audience brief before work begins, approval process and timeline, usage rights, kill fee policy.`,
    defaultDeliverables: [
      "Copy for agreed pages/pieces at specified word count",
      "Delivery in Google Docs format for easy collaboration",
      "Two rounds of revisions included",
      "Final proofread before delivery",
      "Meta descriptions for each page if web copy",
    ],
    commonRisks: [
      "No brand voice guidelines or tone of voice brief provided",
      "Target audience not clearly defined",
      "Word count or scope not specified",
      "Approval process and stakeholders not defined",
      "SEO requirements unclear",
    ],
    defaultClauses: [
      "1. Brief: Client agrees to provide a detailed brief including target audience, tone of voice, key messages, and any existing brand guidelines before work commences.",
      "2. Revisions: This project includes 2 rounds of revisions. Revisions are defined as changes to existing copy — new briefs or significant direction changes are out of scope.",
      "3. Approval: Client agrees to provide feedback within 5 business days. Delays may affect the project timeline.",
      "4. Usage Rights: Upon final payment, the client receives full usage rights to all delivered copy.",
      "5. Kill Fee: If the project is cancelled after the first draft is delivered, 75% of the project fee is due.",
      "6. Credit: The contractor may reference this project in their portfolio unless the client requests otherwise in writing.",
    ],
    clarifyingQuestions: [
      "Do you have a tone of voice guide or brand voice document I can reference?",
      "Who is the primary target audience for this content?",
      "What is the approximate word count needed per page or piece?",
      "Do you need SEO optimization? If so, do you have target keywords?",
      "Who will be approving the copy — one person or a team?",
      "Do you have existing copy that needs refreshing, or is this from scratch?",
    ],
  },
  {
    id: "photography",
    name: "Photography",
    icon: "📷",
    description: "Commercial, product, or portrait photography",
    extractPromptAddition: `This is a photography project. Pay special attention to: number of images required, shooting location, usage rights (web, print, advertising, social), editing and retouching requirements, turnaround time for edited images, raw files included or not, number of shoot days, talent or model requirements. Flag risks around: unlimited image requests, usage rights not defined, location not confirmed, no model releases discussed.`,
    buildPromptAddition: `Generate scope for a photography project. Standard inclusions: agreed shoot duration, agreed number of final edited images, standard retouching, delivery via online gallery, web resolution and print resolution files. Standard exclusions: raw files unless agreed, additional shoot days, model or talent fees, location hire fees, extensive retouching beyond standard. Include clauses about: usage rights definition, model release requirements, weather policy for outdoor shoots, additional usage licensing.`,
    defaultDeliverables: [
      "Photography shoot of agreed duration",
      "Agreed number of final edited images",
      "Standard colour grading and retouching",
      "Delivery via online gallery within agreed timeframe",
      "High resolution and web optimised versions of each image",
    ],
    commonRisks: [
      "Number of final images not defined",
      "Usage rights not specified (social, print, advertising)",
      "Extensive retouching expectations not scoped",
      "Model or talent releases not discussed",
      "Weather contingency for outdoor shoots not addressed",
    ],
    defaultClauses: [
      "1. Usage Rights: Images are licensed for agreed usage only (digital/print/advertising). Additional usage requires a separate licensing agreement.",
      "2. Raw Files: Raw unedited files are not included in this agreement unless specifically stated.",
      "3. Retouching: Standard colour grading and basic retouching is included. Extensive retouching (skin, compositing, background replacement) is billed separately.",
      "4. Weather: For outdoor shoots, a 48-hour postponement notice is required for weather-related cancellations. A rescheduling fee may apply.",
      "5. Model Releases: Client is responsible for obtaining signed model releases from any talent appearing in images.",
      "6. Archive: The photographer retains the right to archive and portfolio display all images unless otherwise agreed.",
    ],
    clarifyingQuestions: [
      "How many final edited images do you require?",
      "Where will these images be used? (website, social media, print advertising, packaging)",
      "Is the shoot location confirmed? Indoor studio or outdoor?",
      "Do you need models or talent? If so, who is responsible for arranging and paying them?",
      "What is your turnaround time expectation for edited images?",
      "Do you need raw files or only edited final images?",
    ],
  },
  {
    id: "video",
    name: "Video Production",
    icon: "🎬",
    description: "Video, animation, and motion graphics",
    extractPromptAddition: `This is a video production project. Pay special attention to: video length and number of videos, format requirements (social, web, broadcast), voiceover or music requirements, number of revision rounds, turnaround time, raw footage ownership, subtitles or captions needed, script responsibility. Flag risks around: unlimited revisions on video, music licensing not discussed, format specifications unclear.`,
    buildPromptAddition: `Generate scope for a video production project. Standard inclusions: agreed video length and format, one round of structural edits, one round of fine cut revisions, colour grade, licensed background music if required, delivery in agreed formats. Standard exclusions: raw footage ownership, broadcast rights, subtitles unless specified, additional versions for different platforms. Include clauses about: revision rounds, music licensing, raw footage ownership, broadcast usage licensing.`,
    defaultDeliverables: [
      "Final edited video of agreed length and format",
      "Colour graded and audio mixed final cut",
      "Delivery in H.264 MP4 for web use",
      "Licensed background music if required",
      "Two rounds of revisions included",
    ],
    commonRisks: [
      "Number of revision rounds not capped",
      "Music licensing costs not discussed",
      "Raw footage ownership not clarified",
      "Platform format requirements not specified",
      "Script or briefing materials not ready",
    ],
    defaultClauses: [
      "1. Revisions: This project includes 2 rounds of revisions. Round 1 covers structural changes. Round 2 covers fine cut adjustments. Additional rounds are billed at the agreed hourly rate.",
      "2. Raw Footage: Raw unedited footage remains the property of the contractor unless a raw footage license is purchased separately.",
      "3. Music: Licensed music is included if specified. The client is responsible for any additional music licensing fees for broadcast or advertising use.",
      "4. Formats: Final delivery is in H.264 MP4 format. Additional formats or resolutions are billed separately.",
      "5. Broadcast: This agreement covers online and social media use only. Broadcast, cinema, or advertising usage requires a separate licensing agreement.",
      "6. Script: Client is responsible for providing an approved script before production begins unless scriptwriting is included in this agreement.",
    ],
    clarifyingQuestions: [
      "What is the required length of the final video?",
      "Where will the video be used? (website, social media, broadcast, advertising)",
      "Do you need a voiceover? If so, will you provide a script or do you need scriptwriting?",
      "Do you need subtitles or captions?",
      "What is your deadline for the final video?",
      "Will you provide footage to edit, or does this include filming?",
    ],
  },
  {
    id: "social-media",
    name: "Social Media",
    icon: "📱",
    description: "Social media management and content creation",
    extractPromptAddition: `This is a social media project. Pay special attention to: which platforms, number of posts per week or month, content creation vs strategy only, copywriting included or not, community management included or not, reporting frequency, ad management included or not, content approval process. Flag risks around: unlimited posting requests, no approval process defined, ad spend management not scoped.`,
    buildPromptAddition: `Generate scope for a social media management project. Standard inclusions: agreed number of posts per month per platform, captions and hashtags, scheduling, monthly performance report. Standard exclusions: ad spend management unless specified, community management unless specified, photography or video production unless specified, influencer management. Include clauses about: content approval process and timeline, ad spend billed separately, platform algorithm changes outside contractor control, minimum contract period.`,
    defaultDeliverables: [
      "Agreed number of posts per month across agreed platforms",
      "Captions, hashtags, and posting schedule",
      "Monthly performance report with key metrics",
      "Content calendar provided 1 week in advance for approval",
    ],
    commonRisks: [
      "Number of posts per platform not defined",
      "Content approval process not established",
      "Community management scope unclear",
      "Paid advertising management not scoped separately",
      "Photography and video for content not addressed",
    ],
    defaultClauses: [
      "1. Approval: Client agrees to approve content calendar within 2 business days. Late approvals may affect posting schedule.",
      "2. Advertising: Paid social media advertising management is not included. Ad spend and management are quoted separately.",
      "3. Performance: Social media results are dependent on many factors outside the contractor's control including platform algorithms and market conditions.",
      "4. Access: Client agrees to provide admin access to all relevant social media accounts before work commences.",
      "5. Minimum Term: This agreement is for a minimum of 3 months. 30 days written notice is required to terminate.",
      "6. Assets: Client is responsible for providing brand assets, product images, and any specific photography required for content.",
    ],
    clarifyingQuestions: [
      "Which social media platforms need to be managed?",
      "How many posts per week or month do you need per platform?",
      "Do you need content creation (graphics, captions) or strategy and management only?",
      "Who approves content before it goes live?",
      "Do you need community management (responding to comments and messages)?",
      "Is paid advertising management included or is this organic content only?",
    ],
  },
  {
    id: "consulting",
    name: "Consulting",
    icon: "💼",
    description: "Strategy, consulting, and advisory services",
    extractPromptAddition: `This is a consulting or strategy project. Pay special attention to: deliverable format (report, presentation, workshop), number of stakeholders involved, access to internal data and teams required, confidentiality requirements, implementation support included or not, number of meetings or workshops. Flag risks around: scope of recommendations vs implementation, access to information not guaranteed, multiple stakeholders with conflicting views.`,
    buildPromptAddition: `Generate scope for a consulting project. Standard inclusions: defined number of discovery sessions, research and analysis, recommendations report or presentation, one round of revisions to final deliverable. Standard exclusions: implementation of recommendations, ongoing advisory unless specified, access to third-party data. Include clauses about: client cooperation and access to information, confidentiality, implementation support quoted separately, intellectual property of methodologies.`,
    defaultDeliverables: [
      "Discovery sessions with key stakeholders",
      "Research and analysis of provided information",
      "Strategic recommendations report or presentation",
      "Executive summary of key findings",
      "One presentation of findings to agreed stakeholders",
    ],
    commonRisks: [
      "Access to internal data and stakeholders not guaranteed",
      "Implementation support scope unclear",
      "Number of stakeholder interviews not defined",
      "Confidentiality requirements not discussed",
      "Decision-making authority of client contact unclear",
    ],
    defaultClauses: [
      "1. Cooperation: Client agrees to provide timely access to relevant team members, data, and information required for this engagement.",
      "2. Implementation: This agreement covers advisory and recommendations only. Implementation support is quoted separately.",
      "3. Confidentiality: Both parties agree to keep all shared information confidential. A separate NDA can be provided on request.",
      "4. Methodology: The contractor's methodologies, frameworks, and tools remain the intellectual property of the contractor.",
      "5. Accuracy: Recommendations are based on information provided by the client. The contractor is not liable for decisions made based on incomplete or inaccurate information.",
      "6. Expenses: Any out-of-pocket expenses (travel, research tools) are billed separately at cost with prior approval.",
    ],
    clarifyingQuestions: [
      "What is the primary outcome or decision this engagement needs to support?",
      "Who are the key stakeholders I will need access to?",
      "What data, reports, or internal documents will be available to me?",
      "Do you need implementation support or recommendations only?",
      "What format should the final deliverable take? (report, presentation, workshop)",
      "Are there any confidentiality or NDA requirements?",
    ],
  },
  {
    id: "general",
    name: "General / Other",
    icon: "⚡",
    description: "Any other type of project",
    extractPromptAddition:
      "Extract all relevant project information and generate appropriate clarifying questions for this type of project.",
    buildPromptAddition:
      "Generate a comprehensive scope for this project with appropriate deliverables, timeline, and contract clauses.",
    defaultDeliverables: [],
    commonRisks: [],
    defaultClauses: [],
    clarifyingQuestions: [],
  },
];

export function getTemplateById(id: string): IndustryTemplate | undefined {
  return INDUSTRY_TEMPLATES.find((t) => t.id === id);
}
